<?php
/**
 * WP Hosting Panel - Configuration Example
 * ==========================================
 * Copy this file as "config.php" and change the values.
 *
 * NOTE: You do NOT need to do this manually!
 * The install.sh script auto-generates config.php.
 * This file is just for reference.
 */

// Panel Settings
define('PANEL_URL', 'http://YOUR_SERVER_IP:8080');
define('PANEL_PORT', 8080);
define('PANEL_NAME', 'WP Hosting Panel');

// JWT Secret (auto-generated by install.sh)
define('JWT_SECRET', 'AUTO_GENERATED_BY_INSTALL');

// SQLite Database (auto-created, no setup needed!)
define('DB_PATH', __DIR__ . '/data/panel.sqlite');

// Server Paths (used after server stack is installed)
define('SITES_HOME', '/home');
define('LSWS_VHOSTS_DIR', '/usr/local/lsws/conf/vhosts');
define('LSWS_CONF_DIR', '/usr/local/lsws/conf');
define('LSWS_VHOST_TEMPLATE', __DIR__ . '/templates/litespeed-vhost.conf');
define('LSWS_PHP_DIR', '/usr/local/lsws/lsphp8');
define('SSL_CERTS_DIR', '/etc/letsencrypt/live');

// OpenLiteSpeed Control
define('LSWS_BIN', '/usr/local/lsws/bin/lswsctrl');
define('LSWS_ADMIN_PORT', 7080);
define('CERTBOT_WEBROOT', '/var/www/html');

// Default PHP Version
define('DEFAULT_PHP', '8.0');

// Available PHP Versions
define('PHP_VERSIONS', '8.0,8.1,8.2,8.3');

// WordPress
define('WP_CLI_PATH', '/usr/local/bin/wp');
define('WP_DEFAULT_THEME', 'twentytwentyfour');

// Security
define('MAX_LOGIN_ATTEMPTS', 5);
define('LOCKOUT_MINUTES', 15);
define('SESSION_EXPIRE_HOURS', 24);

// Timezone
date_default_timezone_set('Asia/Kolkata');

// Error Reporting (disable in production)
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);
ini_set('error_log', __DIR__ . '/logs/error.log');
